doc_comment_code_block_width = 80
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
style_edition = "2024"
unstable_features = true
wrap_comments = true