[package]
name = "test_utilities"
version = "0.1.0"
authors = ["Travis Casey"]
publish = false
edition = "2024"

[lib]
test = false
doc = false
doctest = false
bench = false

[dependencies]
chomp3rs = { version = "0.1.0", path = ".." }
